### ISSUE TITLE
New library

### ISSUE THREAD

**Issue by hfossli** [trailofbits/SecureEnclaveCrypto#11]
I did a total rewrite from ground up and made a new library: https://github.com/agens-no/EllipticCurveKeyPair

I decided to not send a pull request in to this repo because the company I work for is paying for my hours and up until now and I did all the heavy lifting with swift version anyway. I don't violate any license as I wrote everything from ground up. 

Thanks for all support! If you'd like to join as contributors to this repo you are more than welcome. 

Compared to the swift code in this repo
- better structure and api
- better error handling
- [exporting the public key properly](https://forums.developer.apple.com/message/84684#84684)
- signature validates with openssl command (was missing sha256)
- useful copy paste output for validating signatures easily in console
- fallback to keychain on simulator  for faster development

I hope you like it ✨

**Comment by dguido** [comment]
Not cool.

**Comment by hfossli** [comment]
That's a very short response. Feels a bit unfair after all the contribtion, work and effort I've been doing here. I've at the minimum been spending 80 hours on your repo.

**Comment by hfossli** [comment]
I'm giving credits where credits is due in the readme. Let me know if you want some more love :) cc @withzombies
