### ISSUE TITLE
Example doesn't run in Xcode simulator

### ISSUE THREAD

**Issue by btoews** [trailofbits/SecureEnclaveCrypto#2]
I'm trying to get the example running on the Xcode IOS simulator and am getting an exception [here](https://github.com/trailofbits/SecureEnclaveCrypto/blob/8563c68219ba185219bdd1ba2c325dc6bcdcd3c5/KeyInterface/KeyInterface.m#L217). The exception is `Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)`. It seems that `lookupPrivateKeyRef` is returning `nil` [here](https://github.com/trailofbits/SecureEnclaveCrypto/blob/8563c68219ba185219bdd1ba2c325dc6bcdcd3c5/KeyInterface/KeyInterface.m#L94) and `generateKeyPairWithAccessControlObject` is returning `false` [here](https://github.com/trailofbits/SecureEnclaveCrypto/blob/8563c68219ba185219bdd1ba2c325dc6bcdcd3c5/KeyInterface/KeyInterface.m#L152). I'm not used to working with iOS stuff, so I'm not really sure how to debug this further.

I've tried running [another SEC example](https://github.com/crazyquark/KeySafe), but get a parameter error (-50) from `SecKeyGeneratePair`. I'm wondering if SEC doesn't work at all in the iOS simulator?

Any help would be appreciated. I'm running
- Xcode: Version 7.3.1
- Simulator: iPhone 6s / iOS 9.3 (13E230)

Let me know if I can provide any other debugging output or information.

**Comment by withzombies** [comment]
This is due to the simulator not supporting the TouchID interface. There's nothing I can do about it.
